name: Test

on:
  push:
    branches:
      - master
  pull_request:
    # Run on all PRs

env:
  CI: "true"

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dep-version:
          - --prefer-lowest
          - ''
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4-dev'
        psr-log-version:
          - '2.0'
          - '3.0'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          ini-values: zend.assertions=1, assert.exception=1, error_reporting=-1
          php-version: ${{ matrix.php }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}-${{ matrix.php }}-${{ matrix.dep-version }}-${{ matrix.psr-log-version }}
          restore-keys: |
            ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}-${{ matrix.php }}-${{ matrix.dep-version }}
            ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}-${{ matrix.php }}
            ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        run: composer update
          --no-ansi
          --no-interaction
          --no-progress
          --no-suggest
          --prefer-dist
          ${{ matrix.dep-version }}

      - name: Install specific log version
        run: composer update --no-interaction --prefer-dist psr/log:^${{ matrix.psr-log-version }}


      - name: PHPUnit
        run: vendor/bin/phpunit
          --coverage-clover coverage.xml

      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
