name: Test

on:
  push:
    branches:
      - master
  pull_request:
    # Run on all PRs

env:
  CI: "true"

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dep-version:
          - --prefer-lowest
          - ''
        php:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
        psr-log-version:
          - '1.0'
          - '2.0'
        exclude:
          # psr/log:2.0 needs PHP8
          - php: '7.2'
            psr-log-version: '2.0'
          - php: '7.3'
            psr-log-version: '2.0'
          - php: '7.4'
            psr-log-version: '2.0'


    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          ini-values: zend.assertions=1, assert.exception=1, error_reporting=-1
          php-version: ${{ matrix.php }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}-${{ matrix.php }}-${{ matrix.dep-version }}-${{ matrix.psr-log-version }}
          restore-keys: |
            ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}-${{ matrix.php }}-${{ matrix.dep-version }}
            ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}-${{ matrix.php }}
            ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        run: composer update
          --no-ansi
          --no-interaction
          --no-progress
          --no-suggest
          --prefer-dist
          ${{ matrix.dep-version }}

      - name: Install specific log version
        run: composer update --no-interaction --prefer-dist psr/log:^${{ matrix.psr-log-version }}


      - name: PHPUnit
        run: vendor/bin/phpunit
          --coverage-clover coverage.xml

      - name: Submit code coverage
        run: bash <(curl -s https://codecov.io/bash)
